name: Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Locate solution
        id: sln
        run: echo "solution=$(find . -name '*.sln' | head -n1)" >> $GITHUB_OUTPUT
      
      - name: Restore
        run: dotnet restore "${{ steps.sln.outputs.solution }}"
      
      - name: Build
        run: dotnet build "${{ steps.sln.outputs.solution }}" -c Release --no-restore
      
      - name: Test
        run: dotnet test CourseTree/Tests/Tests.csproj --no-build